### ISSUE TITLE
Can I create an application for LiriOS with Electron ?

### ISSUE THREAD

**Issue by meepeek** [lirios/appcenter#9]
LiriOS looks nice. I would like to know since many cross-platform desktop apps created with electron, https://electron.atom.io/apps/. It would be nice if the apps may be ported from those opensource apps available out there.

**Comment by ghost** [comment]
+1 for this

I believe it is possible and fairly simple since electron generates an executable file for Linux; you should just declare the right command to run your app in the `metadata` of flatpak(since it's what lirios uses for app managing):
```
[Application]
name=me.<your name>.<app's name>
runtime=<your favorite runtime, like gnome, etc...>
command=<your electron compiled app>
```
If you don't want to compile the app, you could even use `command=electron <startup file>`, though I don't recommend this

Take a look at this basic example and you'll discover more: http://flatpak.org/hello-world.html

Let's see what @plfiorini thinks

**Comment by plfiorini** [comment]
Technically you can of course I would recommend using Qt + Fluid instead but I'm biased :P
Here you can find a base app for Electron on Flatpak that might be useful: https://github.com/endlessm/electron-flatpak-base-app
